In [ ]:
def lengthConversionA(value):
  """
    Converts length from meters to feet.
    Takes a float value in meters and returns a float value in feet.
   """
  return value * 3.28

def lengthConversionB(value):
  """
    Converts length from feet to meters.
    Takes a float value in feet and returns a float value in meters.
   """
  return value * 0.30

def weightConversionA(value):
  """
    Converts weight from kilograms to pounds.
    Takes a float value in kilograms and returns a float value in pounds.
   """
  return value * 2.2

def weightConversioB(value):
  """
    Converts weight from pounds to kilograms.
    Takes a float value in pounds and returns a float value in kilograms.
   """
  return value * 0.45

def volumeConversionA(value):
  """
    Converts volume from liters to milliliters.
    Takes a float value in liters and returns a float value in milliliters.
   """
  return value * 1000

def volumeConversionB(value):
  """
    Converts volume from milliliters to liters.
    Takes a float value in milliliters and returns a float value in liters.
    """
  return value * 0.001

def main():
        print("Choose a conversion")
        print("1. Length(meters to feet)")
        print("2. Length(feet to meters)")
        print("3. Weight(kilograms to pounds)")
        print("4. Weight(pounds to kilograms)")
        print("5. Volume(liters to milliliters)")
        print("6. Volume(milliliters to liters)")

        choice = int(input("Enter your choice (1-6): "))
        if(choice <= 0 or choice >6):
          print("Invalid choice")
          return
        print("Enter the value you want to convert")
        try:
          value = float(input("Value: "))
        except ValueError:
          print("Invalid value")
          return
        if(choice == 1):
          print(f"{value} m = {lengthConversionA(value)} ft")
        if(choice == 2):
          print(f"{value} ft = {lengthConversionB(value)} m")
        if(choice == 3):
          print(f"{value} kg = {weightConversionA(value)} lbs")
        if(choice == 4):
          print(f"{value} lbs = {weightConversionB(value)} kg")
        if(choice == 5):
          print(f"{value} l = {volumeConversion(value)} ml")
        if(choice == 6):
          print(f"{value} ml = {volumeConversion(value)} l")
        return


if __name__ == "__main__":
    main()

Choose a conversion
1. Length(meters to feet)
2. Length(feet to meters)
3. Weight(kilograms to pounds)
4. Weight(pounds to kilograms)
5. Volume(liters to milliliters)
6. Volume(milliliters to liters)
Enter your choice (1-6): 3
Enter the value you want to convert
Value: 5
5.0 kg = 11.0 lbs


In [ ]:
def sum(lst):
  """
    Calculates the sum of a list of numbers. """
  total = 0
  for num in lst:
    total += num
  return total

def average(lst):
  """
    Calculates the average of a list of numbers. """
  return sum(lst) / len(lst)

def maximum(lst):
  """
    Finds the maximum value in a list of numbers. """
  max_value = lst[0]
  for num in lst:
    if num > max:
      max_value = num
  return max_value

def minimum(lst):
  """
    Finds the minimum value in a list of numbers. """
  min_value = lst[0]
  for num in lst:
    if num < min_value:
      min_value = num
  return min_value



def main():
  print("Choose an operation.\n1.Sum\n2.Average\n3.Maximum\n4.minimum")
  choice = int(input("Enter your choice (1-3): "))
  if(choice <= 0 or choice >4):
    print("Invalid choice")
    return
  while True:
    user_input = input("Enter a list of numbers separated by spaces")

    if not user_input.strip():
      print("Error: Input is empty. Please enter some numbers.")
      continue

    try:
      numbers = [float(item) for item in user_input.split()]
      break

    except ValueError:
      print("Error: Please ensure you only enter numbers separated by spaces.")
  if choice == 1:
    print(f"Sum: {sum(numbers)}")
  if choice == 2:
    print(f"Average: {average(numbers)}")
  if choice == 3:
    print(f"Maximum: {maximum(numbers)}")
  if choice == 4:
    print(f"Minimum: {minimum(numbers)}")
  return
if __name__ == "__main__":
    main()

Choose an operation.
1.Sum
2.Average
3.Maximum
4.minimum
Enter your choice (1-3): 1
Enter a list of numbers separated by spaces1 2 3 4
Sum: 10.0


In [ ]:
#4.2 List Manipulation

my_list = [1, 2, 3, 4, 5, 6]
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other(my_list))

def slice_List(lst, start, end):
    return lst[start:end]

print(slice_List(my_list, 1, 4))

def reverse_list(lst):
  return lst[::-1]

print(reverse_list(my_list))

def remove_first_last(lst):
  return lst[1:-1]

print(remove_first_last(my_list))

def get_first_n(lst, n):
  return lst[:n]

print(get_first_n(my_list, 3))

def get_last_n(lst,n):
  return lst[-n:]

print(get_last_n(my_list, 4))

def reverse_skip(lst):
  return lst[-2::-2]

print(reverse_skip(my_list))

[1, 3, 5]
[2, 3, 4]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]
[3, 4, 5, 6]
[5, 3, 1]


In [ ]:
#4.3.1
nested_list = [[1, 2], [3, 4], [5]]

def flatten_list(lst):
  flattened = []
  for sublist in lst:
    flattened.extend(sublist)
  return flattened

print(flatten_list(nested_list))

[1, 2, 3, 4, 5]


In [ ]:
#4.3.2
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

def access_nested_element(lst, indices):
  return lst[indices[0]][indices[1]]

print(access_nested_element(nested_list, [1, 2]))

6


In [ ]:
#4.3.3
nested_list = [[1, 2], [3, [4, 5]], 6]

def sum_nested_list(lst):
  total = 0
  for item in lst:
    if isinstance(item, list):
      total += sum_nested_list(item)
    else:
      total += item
  return total


print(sum_nested_list(nested_list))

21


In [ ]:
#4.3.4
nested_list = [[1, 2], [3, 2], [4, 5]]
def remove_element(lst, elem):
  for item in lst:
    if isinstance(item, list):
      remove_element(item,elem)
    else:
      if item == elem:
        lst.remove(elem)
  return lst

print(remove_element(nested_list,2))

[[1], [3], [4, 5]]


In [ ]:
#4.3.5
nested_list = [[1, 2], [3, [4, 5]], 6]

def find_max(lst):
  max = 0
  for item in lst:
    if isinstance(item, list):
      max = find_max(item)
    else:
      if item > max:
        max = item
  return max

print(find_max(nested_list))

6


In [ ]:
#4.3.6
nested_list = [[1, 2], [2, 3], [2, 4]]

def count_occurances(lst, elem):
  count = 0
  for item in lst:
    if isinstance(item, list):
      count += count_occurances(item, elem)
    else:
      if item == elem:
        count += 1
  return count

print(count_occurances(nested_list, 2))

3


In [ ]:
#4.3.7
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

def deep_flatted(lst):
  flattened = []
  for item in lst:
    if isinstance(item, list):
      flattened.extend(deep_flatted(item))
    else:
      flattened.append(item)
  return flattened

print(deep_flatted(nested_list))

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
#4.3.8
nested_list = [[1, 2], [3, 4], [5, 6]]

def average_nested(lst):
  sum = 0
  length = 0
  sum += sum_nested_list(lst)
  for item in lst:
    if isinstance(item, list):
      length += len(item)
    else:
      length +=1
  return sum/length

print(average_nested(nested_list))

3.5


In [ ]:
import numpy as np

print("1. Initialize an empty array with size 2x2:")
empty_array = np.empty((2, 2))
print(empty_array)

print("\n2. Initialize an all-one array with size 4x2:")
ones_array = np.ones((4, 2))
print(ones_array)

print("\n3. Return a new array of given shape and type, filled with fill value:")
filled_array = np.full((3, 3), 5)
print(filled_array)

print("\n4. Return a new array of zeros with same shape and type as a given array:")
existing_array = np.array([[1, 2], [3, 4]], dtype=np.int32)
zeros_like_array = np.zeros_like(existing_array)
print("Existing array:\n", existing_array)
print("Zeros-like array:\n", zeros_like_array)

print("\n5. Return a new array of ones with same shape and type as a given array:")
ones_like_array = np.ones_like(existing_array)
print("Existing array:\n", existing_array)
print("Ones-like array:\n", ones_like_array)

print("\n6. For an existing list new_list = [1,2,3,4] convert to a NumPy array:")
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)
print("Original list:", new_list)
print("NumPy array:", numpy_array_from_list)

1. Initialize an empty array with size 2x2:
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

2. Initialize an all-one array with size 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Return a new array of given shape and type, filled with fill value:
[[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Return a new array of zeros with same shape and type as a given array:
Existing array:
 [[1 2]
 [3 4]]
Zeros-like array:
 [[0 0]
 [0 0]]

5. Return a new array of ones with same shape and type as a given array:
Existing array:
 [[1 2]
 [3 4]]
Ones-like array:
 [[1 1]
 [1 1]]

6. For an existing list new_list = [1,2,3,4] convert to a NumPy array:
Original list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]


In [ ]:
print("1. Create an array with values ranging from 10 to 49:")
array_range = np.arange(10, 50)
print(array_range)

print("\n2. Create a 3x3 matrix with values ranging from 0 to 8:")
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

print("\n3. Create a 3x3 identity matrix:")
identity_matrix = np.eye(3)
print(identity_matrix)

print("\n4. Create a random array of size 30 and find its mean:")
random_array_30 = np.random.random(30)
print("Array:\n", random_array_30)
print("Mean:", random_array_30.mean())

print("\n5. Create a 10x10 array with random values and find min/max:")
random_array_10x10 = np.random.random((10, 10))
print("Array:\n", random_array_10x10)
print("Minimum value:", random_array_10x10.min())
print("Maximum value:", random_array_10x10.max())

print("\n6. Create a zero array of size 10 and replace 5th element with 1:")
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

print("\n7. Reverse an array arr = [1,2,0,0,4,0]:")
arr_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr_to_reverse[::-1]
print("Original array:", arr_to_reverse)
print("Reversed array:", reversed_arr)

print("\n8. Create a 2d array with 1 on border and 0 inside:")
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

print("\n9. Create an 8x8 matrix and fill it with a checkerboard pattern:")
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

1. Create an array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. Create a 3x3 matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Create a 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Create a random array of size 30 and find its mean:
Array:
 [0.23659236 0.45914872 0.100002   0.69952104 0.07503487 0.07487588
 0.13863205 0.04099731 0.99255186 0.35556674 0.05214852 0.45223669
 0.93021565 0.63486141 0.11850206 0.78373808 0.92796245 0.26859426
 0.06879861 0.15266603 0.61449364 0.97030467 0.15907995 0.09499339
 0.74021614 0.07442078 0.6833485  0.48792734 0.9276851  0.55990119]
Mean: 0.42916724327483435

5. Create a 10x10 array with random values and find min/max:
Array:
 [[0.21318338 0.47402436 0.21015802 0.77383251 0.75510561 0.2618261
  0.23834985 0.1347516  0.51396232 0.54913434]
 [0.9571447  0.84718265 0.99626085 0.39371499 0.45281158 

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Original arrays:")
print("x =\n", x)
print("y =\n", y)
print("v =", v)
print("w =", w)

print("\n1. Add the two arrays (x + y):")
print(x + y)
print("Add the two arrays (v + w):")
print(v + w)

print("\n2. Subtract the two arrays (x - y):")
print(x - y)
print("Subtract the two arrays (v - w):")
print(v - w)

print("\n3. Multiply array x by 3:")
print(x * 3)

print("\n4. Find the square of each element of array x:")
print(x**2)

print("\n5. Find the dot product between:")
print("   v and w:", np.dot(v, w))
print("   x and v:", np.dot(x, v))
print("   x and y:\n", np.dot(x, y))

print("\n6. Concatenate x and y along row (vstack):")
print(np.vstack((x, y)))

print("Concatenate v and w along column (hstack requires 2D arrays, so reshape):")
print(np.hstack((v.reshape(-1, 1), w.reshape(-1, 1))))

print("\n7. Concatenate x and v:")
try:
    print(np.concatenate((x, v)))
except ValueError as e:
    print(f"Error: {e}")
    print("For concatenating arrays, they need to have same dimensions.")

Original arrays:
x =
 [[1 2]
 [3 5]]
y =
 [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

1. Add the two arrays (x + y):
[[ 6  8]
 [10 13]]
Add the two arrays (v + w):
[20 22]

2. Subtract the two arrays (x - y):
[[-4 -4]
 [-4 -3]]
Subtract the two arrays (v - w):
[-2 -2]

3. Multiply array x by 3:
[[ 3  6]
 [ 9 15]]

4. Find the square of each element of array x:
[[ 1  4]
 [ 9 25]]

5. Find the dot product between:
   v and w: 219
   x and v: [29 77]
   x and y:
 [[19 22]
 [50 58]]

6. Concatenate x and y along row (vstack):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column (hstack requires 2D arrays, so reshape):
[[ 9 11]
 [10 12]]

7. Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
For concatenating arrays, they need to have same dimensions.


In [ ]:
#Matric Operations

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I
print("\n1. Proving A.A^-1 = I:")
inverse_A = np.linalg.inv(A)
product_AA_inv = np.dot(A, inverse_A)
identity_matrix = np.eye(A.shape[0])
print("A Inverse =\n", inverse_A)
print("A * A Inverse=\n", product_AA_inv)
print("Identity matrix (I) =\n", identity_matrix)
print(f"Proved.")

# 2. Prove AB != BA
print("\n2. Proving AB != BA:")
product_AB = np.dot(A, B)
product_BA = np.dot(B, A)
print("A * B =\n", product_AB)
print("B * A =\n", product_BA)
print("A*B != B*A")

# 3. Prove (AB)^T = B^T A^T
print("\n3. Proving (AB)^T = B^T A^T:")
transpose_AB = np.transpose(product_AB)
transpose_B = np.transpose(B)
transpose_A = np.transpose(A)
product_BT_AT = np.dot(transpose_B, transpose_A)
print("(A * B)^T =\n", transpose_AB)
print("B^T * A^T =\n", product_BT_AT)
print("(AB)^T = B^T A^T Proved")

A_coeffs = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

B_consts = np.array([-1, -3, 9])

print("\nCoefficient Matrix A:\n", A_coeffs)
print("Constants Vector B:\n", B_consts)

# Solve using Inverse Methods (X = A^-1 B)
print("\nSolving using Inverse Methods (X = A^-1 B):")

inverse_A_coeffs = np.linalg.inv(A_coeffs)
print("Inverse of A (A^-1):\n", inverse_A_coeffs)

solution_inverse = np.dot(inverse_A_coeffs, B_consts)
print("Solution (x, y, z) from inverse method:", solution_inverse)

# Solve using np.linalg.solve
print("\nSolving using np.linalg.solve:")
solution_solve = np.linalg.solve(A_coeffs, B_consts)
print("Solution (x, y, z) from np.linalg.solve:", solution_solve)

# Verification
print("\nVerification:")
print("A * solution_inverse =", np.dot(A_coeffs, solution_inverse))
print("A * solution_solve =", np.dot(A_coeffs, solution_solve))
print("Original B =", B_consts)
print(f"Are solutions consistent? {np.allclose(solution_inverse, solution_solve)}")


1. Proving A.A^-1 = I:
A Inverse =
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A Inverse=
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix (I) =
 [[1. 0.]
 [0. 1.]]
Proved.

2. Proving AB != BA:
A * B =
 [[23 13]
 [51 29]]
B * A =
 [[36 44]
 [13 16]]
A*B != B*A

3. Proving (AB)^T = B^T A^T:
(A * B)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
(AB)^T = B^T A^T Proved

Coefficient Matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants Vector B:
 [-1 -3  9]

Solving using Inverse Methods (X = A^-1 B):
Inverse of A (A^-1):
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution (x, y, z) from inverse method: [ 2.  1. -2.]

Solving using np.linalg.solve:
Solution (x, y, z) from np.linalg.solve: [ 2.  1. -2.]

Verification:
A * solution_inverse = [-1. -3.  9.]
A * solution_solve = [-1. -3.  9.]
Original B = [-1 -3  9]
Are solutions consistent? True
