In [ ]:
import numpy as np
# initialize an all zero array with size 2 X 3:
zeros_arr = np . zeros ((2 ,3) )
print (" A zeros array is \n", zeros_arr , " with dimensions ", zeros_arr . shape , "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimensions  (2, 3) 



In [ ]:
empty_arr = np.empty((2, 2))
print("An empty array is \n", empty_arr, " with dimensions ", empty_arr.shape, "\n")

all_ones_arr = np.ones((4, 2))
print("An all ones array is \n", all_ones_arr, " with dimensions ", all_ones_arr.shape, "\n")

filled_arr = np.full((2, 3), 5)
print("A filled array is \n", filled_arr, " with dimensions ", filled_arr.shape, "\n")

zeros_arr = np.zeros_like(all_ones_arr)
print("A zeros like array is \n", zeros_arr, " with dimensions ", zeros_arr.shape, "\n")

ones_arr = np.ones_like(all_ones_arr)
print("A ones like array is \n", ones_arr, " with dimensions ", ones_arr.shape, "\n")

new_list = [1, 2, 3, 4, 5, 6, 7, 8]

new_arr = np.array(new_list)

new_2d_arr = new_arr.reshape((4, 2))
print("The reshaped array is \n", new_2d_arr, " with dimensions ", new_2d_arr.shape, "\n")


An empty array is 
 [[4.7872856e-310 0.0000000e+000]
 [9.3460870e-307 0.0000000e+000]]  with dimensions  (2, 2) 

An all ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  with dimensions  (4, 2) 

A filled array is 
 [[5 5 5]
 [5 5 5]]  with dimensions  (2, 3) 

A zeros like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]  with dimensions  (4, 2) 

A ones like array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  with dimensions  (4, 2) 

The reshaped array is 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]  with dimensions  (4, 2) 



In [ ]:
import numpy as np
range_arr = np . arange (10)
print ("An array given range is \n", range_arr , " with dimensions ", range_arr . shape ,"\n")
# return evenly spaced values within a given interval .
linspace_arr = np . linspace (2.0 , 3.0 , num = 5 , endpoint = False )
print ("An evenly spaced array given range is \n", linspace_arr ," with dimensions ",
linspace_arr . shape ,"\n")
7 # return evenly spaced numbers over a specified interval .

An array given range is 
 [0 1 2 3 4 5 6 7 8 9]  with dimensions  (10,) 

An evenly spaced array given range is 
 [2.  2.2 2.4 2.6 2.8]  with dimensions  (5,) 



7

In [ ]:
range_arr = np.arange(10, 50)
print("Array with values ranging from 10 to 49:", range_arr)

matrix_arr = np.arange(0, 9).reshape(3, 3)
print("3X3 matrix with values ranging from 0 to 8:\n", matrix_arr)

identity_matrix = np.eye(3)
print("3X3 identity matrix:\n", identity_matrix)

random_arr = np.random.random(30)
mean_value = random_arr.mean()
print("Random array of size 30:\n", random_arr)
print("Mean of the array:", mean_value)

random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("10X10 array with random values:\n", random_matrix)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Array with values ranging from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3X3 matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3X3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random array of size 30:
 [0.64721865 0.72157636 0.8342155  0.40578429 0.09989024 0.51015697
 0.11799309 0.07574932 0.98444169 0.82339551 0.86196262 0.98492732
 0.72007929 0.27107682 0.01290975 0.50749646 0.48959131 0.51886425
 0.78177565 0.11717677 0.5822299  0.91700445 0.82980006 0.40901513
 0.53699252 0.67869146 0.33015128 0.11925271 0.21288955 0.91766025]
Mean of the array: 0.5339989728929474
10X10 array with random values:
 [[3.24115476e-01 5.58616969e-01 7.04513870e-01 5.18983563e-01
  3.57186929e-01 9.74942544e-01 3.75221507e-05 6.01705985e-02
  4.53732874e-01 8.35008362e-01]
 [7.26737176e-01 3.36608190e-02 3.35108415e-01 5.20815506e-01
  3.92864027e-01 5.64477141e-01 4.88159699e-01 6.357

In [ ]:
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("Zero array with 5th element replaced with 1:\n", zero_arr)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside:\n", border_arr)

checkerboard_arr = np.zeros((8, 8))
checkerboard_arr[1::2, ::2] = 1
checkerboard_arr[::2, 1::2] = 1
print("8X8 checkerboard matrix:\n", checkerboard_arr)


Zero array with 5th element replaced with 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed array: [0 4 0 0 2 1]
2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8X8 checkerboard matrix:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);

In [ ]:
sum_xy = x + y
sum_vw = v + w

print("Sum of x and y:\n", sum_xy)
print("Sum of v and w:\n", sum_vw)

diff_xy = x - y
diff_vw = v - w

print("Difference of x and y:\n", diff_xy)
print("Difference of v and w:\n", diff_vw)

Sum of x and y:
 [[ 6  8]
 [10 13]]
Sum of v and w:
 [20 22]
Difference of x and y:
 [[-4 -4]
 [-4 -3]]
Difference of v and w:
 [-2 -2]


In [ ]:
x_prod = 5*x
y_prod = 5*y
v_prod = 5*v
w_prod = 5*w

print("X*5:",x_prod)
print("Y*5:",y_prod)
print("V*5:",v_prod)
print("W*5:",w_prod)


X*5: [[ 5 10]
 [15 25]]
Y*5: [[25 30]
 [35 40]]
V*5: [45 50]
W*5: [55 60]


In [ ]:

x_squared = x ** 2
y_squared = y ** 2
v_squared = v ** 2
w_squared = w ** 2

print("X squared:", x_squared)
print("Y squared:", y_squared)
print("V squared:", v_squared)
print("W squared:", w_squared)


X squared: [[ 1  4]
 [ 9 25]]
Y squared: [[25 36]
 [49 64]]
V squared: [ 81 100]
W squared: [121 144]


In [ ]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:", dot_xv)
print("Dot product of x and y:", dot_xy)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


In [ ]:
xy_row = np.concatenate((x, y), axis=1)

vw_column = np.vstack((v, w))

print("Concatenated x and y along the row:\n", xy_row)
print("Concatenated v and w along the column:\n", vw_column)


Concatenated x and y along the row:
 [[1 2 5 6]
 [3 5 7 8]]
Concatenated v and w along the column:
 [[ 9 10]
 [11 12]]


In [ ]:
xv_concat = np.concatenate((x,v),axis = 1) #throws error because of different no of dimensions

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A−1 = I
A_inv = np.linalg.inv(A)
identity = np.eye(2)

result = np.dot(A, A_inv)
print(A)
print("A.A^-1:\n", result)
print("Identity matrix:\n", identity)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("BA:\n", BA)

# 3. Prove (AB)ᵀ = BᵀAᵀ
AT = A.transpose()
BT = B.transpose()

ABT = np.dot(A, B).transpose()
BTAT = np.dot(BT, AT)

print("(AB)ᵀ:\n", ABT)
print("BᵀAᵀ:\n", BTAT)


[[3 4]
 [7 8]]
A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix:
 [[1. 0.]
 [0. 1.]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
(AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]


In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([[-1], [-3], [9]])

#A inverse
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

print("The solution to the system of linear equations is:")
print(X)


The solution to the system of linear equations is:
[[ 2.]
 [ 1.]
 [-2.]]


In [ ]:
# Transforming in - built data structures - DataFrame
# Style -1
import pandas as pd
df1 = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})
print(df1)
# Style -2
df2 = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']},index =[ 'Product A', 'Product B'])
print(df2)

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.
                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.


In [ ]:
# Importing Data from file
import pandas as pd
# path to your dataset must be given to built in read_csv (" Your path ") function .
dataset = pd . read_csv ("/data/Week03/bank .csv ")
dataset . head ()
dataset . tail ()
dataset . info ()
# Run the above code and observe the output .

FileNotFoundError: [Errno 2] No such file or directory: '/data/Week03/bank .csv '

In [ ]:
data = {'Name': ['Alice ', 'Bob ', 'Charlie '] ,'City': ['New York ', 'San Francisco ', 'Los Angeles ']}
df = pd . DataFrame ( data ) # creating a DataFrame
# Writing DataFrame to csv.
df . to_csv ('output .csv ', index = False )
# Run the above code and observe the output

In [ ]:
# Assuming df is your DataFrame
data = {'Name ': ['Alice ', 'Bob ', 'Charlie '] ,'City ': ['New York ', 'San Francisco ', 'LosAngeles ']}
df = pd . DataFrame ( data )
# Drop a specific row by index
df = df . drop (1)
# Drop rows based on a condition .
df = df [ df ['City '] == "New York "]
# Reset index after dropping rows
df = df . reset_index ( drop = True )

In [ ]:
import pandas as pd
# Assuming df is your DataFrame
data = {'Name ': ['Alice ', 'Bob ', 'Charlie '] ,'City': ['New York ', 'San Francisco ', 'LosAngeles ']}
df = pd . DataFrame ( data )
# Drop a specific column by name
df = df . drop ('City', axis =1)
# Drop multiple columns by names
#df = df . drop ([ 'Name ', 'City'] , axis =1)
# Drop columns by index
df = df . drop ( df . columns [0] , axis =1)

In [ ]:
import pandas as pd
from sklearn . datasets import load_iris
import numpy as np
iris = load_iris () # Load the Iris dataset
iris_df = pd.DataFrame(data=np.c_[iris['data'], iris['target']],
                       columns=iris['feature_names'] + ['target'])
np . random . seed (42) # Introduce missing values randomly
mask = np . random . rand (* iris_df . shape ) < 0.1 # 10%
iris_df [ mask ] = np . nan
print (" Missing Values in Iris Dataset :")
print ( iris_df . isnull () .sum () )

In [ ]:
# Contd from code @ slide 18
# Filling missing values with forward fill ( ffill ), mean , median , and 0
iris_df_ffill = iris_df . ffill ()
iris_df_mean = iris_df . fillna ( iris_df . mean () )
iris_df_median = iris_df . fillna ( iris_df . median () )
iris_df_zero = iris_df . fillna (0)
# Expand iris_df with filled columns
iris_df_expanded = pd . concat ([ iris_df , iris_df_ffill . add_suffix ('_ffill ') , iris_df_mean .
add_suffix ('_mean ') , iris_df_median . add_suffix ('_median ') , iris_df_zero . add_suffix ('_zero ') ] , axis =1)
# Display the head of the expanded DataFrame
print ("\ nDataset after Filling Missing Values :")
print ( iris_df_expanded . head () )

NameError: name 'iris_df' is not defined

In [ ]:
import pandas as pd
from sklearn . datasets import load_iris
iris = load_iris () # Load the Iris dataset
iris_df = pd . DataFrame ( data = iris ['data'] , columns = iris ['feature_names'])
# Standard Scaling
iris_standard_scaled = ( iris_df - iris_df . mean () ) / iris_df . std ()
print (" Original Iris DataFrame :")
print ( iris_df . head () )
print ("\ nStandard Scaled Iris DataFrame :")
print ( iris_standard_scaled . head () ) # Display scaled data

 Original Iris DataFrame :
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
\ nStandard Scaled Iris DataFrame :
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.897674          1.015602          -1.335752         -1.311052
1          -1.139200         -0.131539          -1.335752         -1.311052
2          -1.380727          0.327318          -1.392399         -1.311052
3          -1.501490          0.097889          -1.279104         -1.311052
4          -1.018437          1.245030          -1.335752         -1.311052


In [ ]:
import pandas as pd
from sklearn . datasets import load_iris
iris = load_iris () # Load the Iris dataset
iris_df = pd . DataFrame ( data = iris ['data'] , columns = iris ['feature_names'])
# Min -Max Scaling using Pandas
iris_minmax_scaled = ( iris_df - iris_df .min () ) / ( iris_df .max () - iris_df . min () )
print (" Original Iris DataFrame :")
print ( iris_df . head () )
print ("\nMin -Max Scaled Iris DataFrame :")
print ( iris_minmax_scaled . head () ) # Display scaled data

 Original Iris DataFrame :
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Min -Max Scaled Iris DataFrame :
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667


In [ ]:
import pandas as pd
# Sample DataFrame with ordinal categories
df = pd . DataFrame ({ 'Category ': ['Low ', 'Medium ', 'High ', 'Low ', 'High ']})
# Ordinal encoding using map
ordinal_mapping = {'Low ': 1 , 'Medium ': 2 , 'High ': 3}
df [' Category_Ordinal '] = df ['Category ']. map ( ordinal_mapping )
print ( df )

  Category    Category_Ordinal 
0      Low                    1
1   Medium                    2
2     High                    3
3      Low                    1
4     High                    3


In [ ]:
import pandas as pd
df_municipalities = pd . DataFrame ({ ' Municipality ': ['Kathmandu ', 'Bhaktapur ', 'Lalitpur ','Madhyapur Thimi ', 'Kirtipur ']})
one_hot_encoding = pd . get_dummies ( df_municipalities [' Municipality '] , prefix ='Municipality ')
df_encoded = pd . concat ([ df_municipalities , one_hot_encoding ] , axis =1)
print ( df_encoded )# Display the result

      Municipality   Municipality _Bhaktapur   Municipality _Kathmandu   \
0        Kathmandu                      False                      True   
1        Bhaktapur                       True                     False   
2         Lalitpur                      False                     False   
3  Madhyapur Thimi                      False                     False   
4         Kirtipur                      False                     False   

   Municipality _Kirtipur   Municipality _Lalitpur   \
0                    False                    False   
1                    False                    False   
2                    False                     True   
3                    False                    False   
4                     True                    False   

   Municipality _Madhyapur Thimi   
0                           False  
1                           False  
2                           False  
3                            True  
4                           False  
